openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.0
servers:
  - url: https://example.com
    description: example server
paths:
  "/apps": # 1 エンドポイント /apps の定義
    get:
      responses:
        "200": # 2 ステータスコードが 200 の定義
          description: example
          content:
            "application/json": # 3 JSON を返すときの定義
              schema: # 4 レスポンスの JSON 構造
                type: array
                items:
                  "$ref": "#/components/schemas/App"
    post:
      requestBody:
        content:
          "application/json":
            schema:
              "$ref": "#/components/schemas/App"
      responses:
        "200":
          description: created response
          content:
            "application/json":
              schema:
                "$ref": "#/components/schemas/App"
  "/apps/{id}":
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      responses:
        "200":
          "$ref": "#/components/responses/AppResponse"

components:
  responses:
    AppResponse:
      description: app response
      content:
        "application/json":
          schema:
            "$ref": "#/components/schemas/App"
  schemas:
    App:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        price:
          type: integer
